patreon: mannysoft
tidelift: npm/mannysoft
open_collective: 
ko_fi: famypos
community_bridge: 
liberapay:
issuehunt: mannysoft
otechie:
lfx_crowdfunding: 
custom: ["https://www.paypal.me/mannyisles", mannyisles.com]
